name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install packages
      run: apt-get install lilypond
    - name: build
      run: make
    - uses: actions/upload-artifact@v2
      with:
        name: pdfs
        path: *.pdf